/**
 * Grundwissens-Fragenpool für Chemie 8. Klasse
 * 50 Multiple-Choice-Fragen aus den Themen:
 *   - Stoffe (Reinstoff, Gemisch, Element, Verbindung, Trennverfahren)
 *   - Aggregatzustände & Phasenübergänge
 *   - Energie (exotherm, endotherm, Aktivierungsenergie)
 *   - Atombau-Grundlagen
 *   - Chemische Reaktion vs. physikalischer Vorgang
 *   - Stöchiometrie / Reaktionsgleichungen (sehr basic)
 *
 * Format: { f: Frage, a: [Antworten], r: Index der richtigen Antwort, e: kurze Erklärung }
 */
window.GRUNDWISSEN_POOL = [
  // --- Stoffe (1-10) ---
  { f: "Was ist ein Reinstoff?",
    a: ["Ein Stoff aus mehreren verschiedenen Bestandteilen", "Ein Stoff, der aus nur einer Stoffart besteht", "Ein besonders sauberer Stoff", "Ein Stoff ohne Schmutz"],
    r: 1,
    e: "Ein Reinstoff besteht aus nur einer einzigen Stoffart und hat einheitliche Eigenschaften (z.B. Schmelzpunkt)." },
  { f: "Welches der folgenden ist ein Gemisch?",
    a: ["Destilliertes Wasser", "Sauerstoff", "Mineralwasser", "Eisen"],
    r: 2,
    e: "Mineralwasser enthält Wasser plus gelöste Salze und Kohlensäure — also mehrere Stoffe gemischt." },
  { f: "Welches ist ein Element?",
    a: ["Wasser", "Kupfer", "Salz", "Luft"],
    r: 1,
    e: "Kupfer (Cu) besteht nur aus Kupfer-Atomen und ist daher ein Element." },
  { f: "Welches ist eine Verbindung?",
    a: ["Wasserstoff", "Gold", "Wasser", "Helium"],
    r: 2,
    e: "Wasser (H₂O) besteht aus Wasserstoff- UND Sauerstoff-Atomen, ist also eine Verbindung." },
  { f: "Mit welchem Verfahren trennt man Salz von Wasser?",
    a: ["Filtrieren", "Eindampfen", "Magnetscheidung", "Sieben"],
    r: 1,
    e: "Beim Eindampfen verdampft das Wasser, das Salz bleibt zurück." },
  { f: "Mit welchem Verfahren trennt man Sand von Wasser?",
    a: ["Filtrieren", "Destillieren", "Eindampfen", "Extrahieren"],
    r: 0,
    e: "Sand bleibt im Filter zurück, das Wasser läuft durch — klassisches Filtrieren." },
  { f: "Welches Gemisch ist heterogen?",
    a: ["Salzwasser", "Sand-Wasser-Gemisch", "Luft", "Zuckerwasser"],
    r: 1,
    e: "Beim Sand-Wasser-Gemisch erkennt man die Bestandteile mit dem Auge — also heterogen." },
  { f: "Eine Lösung ist ein …",
    a: "homogenes Gemisch / heterogenes Gemisch / Reinstoff / Element".split(" / "),
    r: 0,
    e: "Eine Lösung (z.B. Salzwasser) ist gleichmäßig durchmischt — das heißt homogen." },
  { f: "Mit welchem Verfahren trennt man zwei Flüssigkeiten mit unterschiedlichem Siedepunkt?",
    a: ["Filtrieren", "Destillieren", "Sieben", "Magnetscheidung"],
    r: 1,
    e: "Beim Destillieren wird die Flüssigkeit mit dem niedrigeren Siedepunkt zuerst verdampft und dann wieder kondensiert." },
  { f: "Luft ist …",
    a: ["ein Element", "eine Verbindung", "ein Reinstoff", "ein Gemisch"],
    r: 3,
    e: "Luft besteht aus Stickstoff, Sauerstoff, CO₂ und weiteren Gasen — also ein Gemisch (homogen)." },

  // --- Aggregatzustände (11-18) ---
  { f: "Wie heißt der Übergang von fest zu flüssig?",
    a: ["Sieden", "Schmelzen", "Sublimieren", "Erstarren"],
    r: 1,
    e: "Schmelzen: fest → flüssig (z.B. Eis wird zu Wasser bei 0 °C)." },
  { f: "Wie heißt der Übergang von flüssig zu gasförmig?",
    a: ["Verdampfen", "Kondensieren", "Resublimieren", "Erstarren"],
    r: 0,
    e: "Verdampfen (oder Sieden): flüssig → gasförmig." },
  { f: "Wie heißt der Übergang von gasförmig zu flüssig?",
    a: ["Verdampfen", "Schmelzen", "Kondensieren", "Sublimieren"],
    r: 2,
    e: "Kondensieren: gasförmig → flüssig (z.B. Wasserdampf wird zu Wassertropfen am kalten Glas)." },
  { f: "Wie heißt der direkte Übergang von fest zu gasförmig?",
    a: ["Verdampfen", "Kondensieren", "Sublimieren", "Erstarren"],
    r: 2,
    e: "Sublimieren: fest → gasförmig direkt, ohne flüssige Zwischenstufe (z.B. Trockeneis)." },
  { f: "Im festen Zustand sind die Teilchen …",
    a: ["weit voneinander entfernt", "in regelmäßiger Anordnung dicht gepackt", "frei beweglich", "gar nicht vorhanden"],
    r: 1,
    e: "Im Feststoff sitzen die Teilchen auf festen Plätzen und schwingen nur leicht." },
  { f: "Im gasförmigen Zustand sind die Teilchen …",
    a: ["unbeweglich", "dicht gepackt", "weit voneinander entfernt und schnell", "in einer Reihe"],
    r: 2,
    e: "Gas-Teilchen bewegen sich mit großen Abständen sehr schnell durch den ganzen Raum." },
  { f: "Was passiert beim Erstarren?",
    a: ["flüssig → gasförmig", "flüssig → fest", "fest → flüssig", "gasförmig → fest"],
    r: 1,
    e: "Erstarren: flüssig → fest (z.B. Wasser zu Eis bei 0 °C)." },
  { f: "Bei welcher Temperatur erstarrt Wasser unter Normalbedingungen?",
    a: ["100 °C", "0 °C", "−10 °C", "20 °C"],
    r: 1,
    e: "Wasser erstarrt bei 0 °C zu Eis (und schmilzt bei der gleichen Temperatur)." },

  // --- Energie (19-26) ---
  { f: "Was bedeutet exotherm?",
    a: ["Energie wird aufgenommen", "Energie wird abgegeben", "Keine Energie wird umgesetzt", "Wärme verschwindet"],
    r: 1,
    e: "Exotherm = Energie (meist Wärme) wird an die Umgebung abgegeben. Beispiel: Verbrennung." },
  { f: "Was bedeutet endotherm?",
    a: ["Energie wird abgegeben", "Energie wird aufgenommen", "Keine Energie wird umgesetzt", "Es entsteht Licht"],
    r: 1,
    e: "Endotherm = Energie (meist Wärme) muss aus der Umgebung aufgenommen werden. Beispiel: Schmelzen von Eis." },
  { f: "Welche Reaktion ist exotherm?",
    a: ["Schmelzen von Eis", "Verbrennung von Holz", "Backen eines Kuchens", "Fotosynthese"],
    r: 1,
    e: "Beim Verbrennen wird viel Wärme und Licht abgegeben — also exotherm." },
  { f: "Welche Reaktion ist endotherm?",
    a: ["Verbrennung von Benzin", "Schmelzen von Eis", "Rosten von Eisen", "Knallgasreaktion"],
    r: 1,
    e: "Schmelzen braucht Energie (Wärme), die aufgenommen wird — also endotherm." },
  { f: "Was ist die Aktivierungsenergie?",
    a: ["Die Energie, die bei der Reaktion frei wird", "Die Mindest-Energie, die nötig ist, damit eine Reaktion startet", "Die Energie der Edukte", "Die gespeicherte Energie der Produkte"],
    r: 1,
    e: "Die Aktivierungsenergie ist der \"Anschub\" — z.B. ein Streichholz braucht erst Reibungswärme, bevor es brennt." },
  { f: "Holz brennt erst, wenn man es entzündet. Warum?",
    a: ["Weil die Reaktion endotherm ist", "Weil eine Aktivierungsenergie nötig ist", "Weil Holz immer Wasser enthält", "Weil Sauerstoff fehlt"],
    r: 1,
    e: "Auch exotherme Reaktionen brauchen oft erst einen Energie-Anschub (Aktivierungsenergie) zum Starten." },
  { f: "Bei einer exothermen Reaktion …",
    a: ["sind die Produkte energiereicher als die Edukte", "sind die Edukte energiereicher als die Produkte", "haben Edukte und Produkte gleich viel Energie", "wird gar keine Energie umgesetzt"],
    r: 1,
    e: "Wenn Energie abgegeben wird, müssen die Edukte vorher mehr Energie gehabt haben als die Produkte danach." },
  { f: "Welche Energieform wird bei chemischen Reaktionen oft frei?",
    a: ["Schallenergie", "Wärmeenergie", "Magnetische Energie", "Kernenergie"],
    r: 1,
    e: "Wärme ist die häufigste Energieform bei chemischen Reaktionen, oft auch Licht und elektrische Energie." },

  // --- Atombau (27-36) ---
  { f: "Woraus besteht ein Atom hauptsächlich?",
    a: ["Aus dem Kern und der Hülle", "Nur aus dem Kern", "Nur aus Elektronen", "Aus Molekülen"],
    r: 0,
    e: "Ein Atom hat einen sehr kleinen, schweren Atomkern und eine große, fast leere Atomhülle." },
  { f: "Welche Teilchen befinden sich im Atomkern?",
    a: ["Elektronen", "Protonen und Neutronen", "Nur Neutronen", "Ionen"],
    r: 1,
    e: "Im Kern sitzen die positiv geladenen Protonen und die ungeladenen Neutronen." },
  { f: "Welche Teilchen befinden sich in der Atomhülle?",
    a: ["Protonen", "Neutronen", "Elektronen", "Ionen"],
    r: 2,
    e: "Die negativ geladenen Elektronen umkreisen den Kern in der Atomhülle." },
  { f: "Welche Ladung hat ein Proton?",
    a: ["negativ", "positiv", "neutral", "es ist mal so, mal so"],
    r: 1,
    e: "Protonen sind positiv geladen (+)." },
  { f: "Welche Ladung hat ein Elektron?",
    a: ["positiv", "negativ", "neutral", "doppelt positiv"],
    r: 1,
    e: "Elektronen sind negativ geladen (−)." },
  { f: "Welche Ladung hat ein Neutron?",
    a: ["positiv", "negativ", "neutral", "wechselnd"],
    r: 2,
    e: "Neutronen sind neutral, daher der Name." },
  { f: "Wie ist das Periodensystem geordnet?",
    a: ["Nach dem Alphabet", "Nach steigender Ordnungszahl (Protonenzahl)", "Nach Größe der Atome", "Nach Erfindungsdatum"],
    r: 1,
    e: "Die Ordnungszahl gibt die Anzahl der Protonen im Kern an — danach ist das PSE sortiert." },
  { f: "Was sagt die Ordnungszahl eines Elements aus?",
    a: ["Die Masse des Atoms", "Die Anzahl der Protonen im Kern", "Die Anzahl der Neutronen", "Den Schmelzpunkt"],
    r: 1,
    e: "Ordnungszahl = Anzahl Protonen. In neutralen Atomen ist sie auch gleich der Anzahl der Elektronen." },
  { f: "Wie viele Protonen hat ein Sauerstoff-Atom (Ordnungszahl 8)?",
    a: ["6", "7", "8", "16"],
    r: 2,
    e: "Die Ordnungszahl gibt direkt die Protonenzahl an — also 8 Protonen." },
  { f: "Ein Atom ist nach außen elektrisch …",
    a: ["positiv", "negativ", "neutral, weil gleich viele Protonen und Elektronen", "neutral, weil keine geladenen Teilchen vorhanden sind"],
    r: 2,
    e: "Im neutralen Atom heben sich die positiven Protonen und negativen Elektronen genau auf." },

  // --- Reaktion vs. physikal. Vorgang (37-44) ---
  { f: "Was ist eine chemische Reaktion?",
    a: ["Ein Vorgang, bei dem neue Stoffe entstehen", "Ein Vorgang, bei dem nur die Form sich ändert", "Schmelzen oder Sieden", "Ein Mischen von Stoffen"],
    r: 0,
    e: "Bei einer chem. Reaktion entstehen Stoffe mit neuen Eigenschaften — Edukte werden zu Produkten." },
  { f: "Welcher Vorgang ist eine chemische Reaktion?",
    a: ["Eis schmilzt zu Wasser", "Zucker löst sich in Wasser", "Holz verbrennt zu Asche und Rauch", "Wasser verdampft"],
    r: 2,
    e: "Beim Verbrennen entstehen neue Stoffe (CO₂, Wasserdampf, Asche) — chemische Reaktion." },
  { f: "Welcher Vorgang ist KEINE chemische Reaktion?",
    a: ["Rosten von Eisen", "Verbrennen von Papier", "Schmelzen von Eis", "Verdauen von Nahrung"],
    r: 2,
    e: "Beim Schmelzen ändert sich nur der Aggregatzustand, der Stoff (H₂O) bleibt gleich — physikalischer Vorgang." },
  { f: "Welcher Vorgang ist ein physikalischer Vorgang?",
    a: ["Eisen rostet", "Wasser kocht", "Magnesium verbrennt", "Backpulver reagiert mit Essig"],
    r: 1,
    e: "Beim Kochen ändert Wasser nur den Aggregatzustand — chemisch bleibt es H₂O." },
  { f: "Woran erkennst du eine chemische Reaktion?",
    a: ["Es entstehen neue Stoffe mit neuen Eigenschaften", "Der Stoff ändert nur die Form", "Es wird nichts verändert", "Nur die Temperatur ändert sich"],
    r: 0,
    e: "Hinweise: Farbänderung, Gasentwicklung, Niederschlag, Wärme/Licht — und neue Stoffe." },
  { f: "Stoffe, die in eine chemische Reaktion hineingehen, heißen …",
    a: ["Produkte", "Edukte", "Reagenzien", "Katalysatoren"],
    r: 1,
    e: "Edukte → Produkte. Die Edukte sind die Ausgangsstoffe." },
  { f: "Stoffe, die bei einer chemischen Reaktion neu entstehen, heißen …",
    a: ["Edukte", "Produkte", "Reaktanten", "Katalysatoren"],
    r: 1,
    e: "Edukte → Produkte. Die Produkte sind die neu entstandenen Stoffe." },
  { f: "Beim Erhitzen schmilzt Schokolade. Das ist …",
    a: ["eine chemische Reaktion", "ein physikalischer Vorgang", "eine Verbrennung", "eine endotherme Reaktion mit neuen Stoffen"],
    r: 1,
    e: "Schmelzen ist nur ein Aggregatzustands-Wechsel — kein neuer Stoff entsteht. Physikalisch." },

  // --- Stöchiometrie / Reaktionsgleichungen (45-50) ---
  { f: "Was ist die richtige Reaktionsgleichung für Wasser-Bildung?",
    a: ["H + O → H₂O", "2 H₂ + O₂ → 2 H₂O", "H₂ + O → H₂O", "H₂O → H₂ + O₂"],
    r: 1,
    e: "Aus 2 Wasserstoff-Molekülen + 1 Sauerstoff-Molekül entstehen 2 Wasser-Moleküle." },
  { f: "Warum müssen Reaktionsgleichungen ausgeglichen sein?",
    a: ["Damit es schöner aussieht", "Wegen des Gesetzes der Erhaltung der Masse", "Damit man weniger schreiben muss", "Es ist egal"],
    r: 1,
    e: "Es darf kein Atom verloren gehen — links und rechts vom Pfeil müssen gleich viele Atome jeder Sorte stehen." },
  { f: 'Was bedeutet die Zahl 2 vor H₂O in „2 H₂O"?',
    a: ["2 Wasserstoffatome", "2 Sauerstoffatome", "2 Wassermoleküle", "Doppelt so schwer"],
    r: 2,
    e: "Die Koeffizientenzahl vorne gibt die Anzahl der Moleküle an: 2 Wassermoleküle." },
  { f: "Was bedeutet die kleine 2 in H₂O?",
    a: ["2 Wassermoleküle", "2 Wasserstoffatome im Molekül", "2 Sauerstoffatome", "Aggregatzustand"],
    r: 1,
    e: "Die tiefgestellte Zahl zählt die Atome im Molekül: H₂O = 2 Wasserstoff- und 1 Sauerstoffatom." },
  { f: "Wie viele Atome enthält ein Molekül CO₂?",
    a: ["2", "3", "4", "1"],
    r: 1,
    e: "1 Kohlenstoff-Atom + 2 Sauerstoff-Atome = 3 Atome insgesamt." },
  { f: "Welche Aussage zum Gesetz der Erhaltung der Masse stimmt?",
    a: ["Bei chemischen Reaktionen entsteht Masse", "Bei chemischen Reaktionen geht Masse verloren", "Die Gesamtmasse der Edukte = Gesamtmasse der Produkte", "Nur bei Verbrennungen verschwindet Masse"],
    r: 2,
    e: "Masse kann nicht entstehen oder verschwinden — sie bleibt erhalten (Gesetz von Lavoisier)." },
];
